-- CreateEnum
CREATE TYPE "WorkType" AS ENUM ('JOURNAL', 'BOOK', 'GENERIC', 'WEB_PAGE', 'THESIS', 'STATUTE', 'CASE', 'BOOK_SECTION', 'MAGAZINE_ARTICLE', 'ENCYCLOPEDIA_ARTICLE');

-- AlterTable
ALTER TABLE "Work" ADD COLUMN     "tags" TEXT[],
ADD COLUMN     "type" "WorkType" NOT NULL DEFAULT 'GENERIC';
