export enum Role {
  SUPER,
  ADMIN,
  USER,
}

export enum ExponatKind {
  PROCARIOT,
  EUCARIOT,
  MINERAL,
}

export enum MemberRole {
  ADMIN,
  MEMBER,
}

export enum County {
  SPLITSKO_DALMATINSKA = "SPLITSKO_DALMATINSKA",
  DUBROVACKO_NERETVANSKA = "DUBROVACKO_NERETVANSKA",
  SIBENSKO_KNINSKA = "SIBENSKO_KNINSKA",
  ZADARSKA = "ZADARSKA",
  ZAGREBACKA = "ZAGREBACKA",
  KARLOVACKA = "KARLOVACKA",
  VARAZDINSKA = "VARAZDINSKA",
  KOPRIVNICKO_KRIZEVACKA = "KOPRIVNICKO_KRIZEVACKA",
  KRAPINSKO_ZAGORSKA = "KRAPINSKO_ZAGORSKA",
  MEDIMURSKA = "MEDIMURSKA",
  OSIJECKO_BARANJSKA = "OSIJECKO_BARANJSKA",
  POZESKO_SLAVONSKA = "POZESKO_SLAVONSKA",
  PRIMORSKO_GORANSKA = "PRIMORSKO_GORANSKA",
  SISACKO_MOSLAVACKA = "SISACKO_MOSLAVACKA",
  VUKOVARSKO_SRIJEMSKA = "VUKOVARSKO_SRIJEMSKA",
  GRAD_ZAGREB = "GRAD_ZAGREB",
  BJELOVARSKO_BILOGORSKA = "BJELOVARSKO_BILOGORSKA",
  BRODSKO_POSAVSKA = "BRODSKO_POSAVSKA",
  ISTARSKA = "ISTARSKA",
  LICKO_SENJSKA = "LICKO_SENJSKA",
  VIROVITICKO_PODRAVSKA  = "VIROVITICKO_PODRAVSKA",
  OTHER = "OTHER"
}

export enum AdminApprovalRequestType {
  ORGANISATION,
  EXPONAT,
  MEMBER,
  POST
}
