export enum Role {
  SUPER,
  ADMIN,
  USER,
}

export enum ExponatKind {
  PROCARIOT,
  EUCARIOT,
  MINERAL,
}

export enum MemberRole {
  ADMIN,
  MEMBER,
}

export enum County {
  SPLITSKO_DALMATINSKA,
  DUBROVACKO_NERETVANSKA,
  SIBENSKO_KNINSKA,
  ZADARSKA,
  ZAGREBACKA,
  KARLOVACKA,
  VARAZDINSKA,
  KOPRIVNICKO_KRIZEVACKA,
  KRAPINSKO_ZAGORSKA,
  MEDIMURSKA,
  OSIJECKO_BARANJSKA,
  POZESKO_SLAVONSKA,
  PRIMORSKO_GORANSKA,
  SISACKO_MOSLAVACKA,
  VUKOVARSKO_SRIJEMSKA,
  GRAD_ZAGREB,
  BJELOVARSKO_BILOGORSKA,
  BRODSKO_POSAVSKA,
  ISTARSKA,
  LICKO_SENJSKA,
  VIROVITICKO_PODRAVSKA,
  OTHER,
}
