version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - 80:80
    depends_on:
      - postgres
    volumes:
      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=biosfera
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    container_name: api_container
    ports:
      - "5500:5500"
    depends_on:
      - postgres
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      dockerfile: ./apps/api/Dockerfile
      target: runner
    env_file:
      - ./.env
  web:
    container_name: web_container
    ports:
      - "3000:3000"
    depends_on:
      - api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      dockerfile: ./apps/web/Dockerfile
      target: runner
      args:
        - WEB_URL=${WEB_URL:-http://localhost:3000}
    env_file:
      - ./.env

volumes:
  db_data:
