version = 1

exclude_patterns = [
  "**/seed.ts",
  "seed.ts",
  "prisma/seed.ts"
]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["nodejs"]

[[transformers]]
name = "prettier"